site_name: Alis Akers
site_description: Alis Akers - DevOps engineer, open-source, cloud-native technologies, public health.
site_url: https://alismx.dev
repo_url: https://github.com/alismx/alismx.github.io
repo_name: alismx/alismx.github.io

docs_dir: docs

nav:
  - profile: index.md
  - posts:
    - blog/index.md

plugins:
  - search
  - offline
  - privacy
  - tags
  - blog:
      blog_dir: blog
      post_readtime: true

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  language: en
  features:
    - content.code.copy
    - toc.integrate
    - search.share
    - header.autohide
    - navigation.footer
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alismx
  copyright: Copyright &copy; 2015 - 2026 Alis Akers

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
